name: Create and Release Mods

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step to extract the version number from the tag
      - name: Get version number
        id: get_version
        run: |
          # github.ref_name gives us 'v1.0.0' or 'v2.1.0-beta', etc.
          # We'll remove the leading 'v' to get just '1.0.0'
          VERSION=${{ github.ref_name }}
          VERSION_NUMBER=$(echo "$VERSION" | sed 's/^v//')
          echo "Extracted version number: $VERSION_NUMBER"
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_OUTPUT # Store as an output

      - name: Create SupersStoryStrings Mod
        run: |
          # Use the version number output from the previous step
          VERSION_SUFFIX="${{ steps.get_version.outputs.VERSION_NUMBER }}"
          MOD_FILENAME="SupersStoryStrings-$VERSION_SUFFIX.mod"

          cd SupersStoryStrings/
          zip -r -q "../${MOD_FILENAME}.zip" . # Use the full filename for the zip
          cd ../
          mv "${MOD_FILENAME}.zip" "${MOD_FILENAME}" # Rename .zip to .mod (it's already .mod)
          echo "SupersStoryStrings Mod created: ${MOD_FILENAME}"
        working-directory: ${{ github.workspace }}

      - name: Create SupersSpeedStrings Mod
        run: |
          # Use the version number output from the previous step
          VERSION_SUFFIX="${{ steps.get_version.outputs.VERSION_NUMBER }}"
          MOD_FILENAME="SupersSpeedStrings-$VERSION_SUFFIX.mod"

          cd SupersSpeedStrings/
          zip -r -q "../${MOD_FILENAME}.zip" .
          cd ../
          mv "${MOD_FILENAME}.zip" "${MOD_FILENAME}"
          echo "SupersSpeedStrings Mod created: ${MOD_FILENAME}"
        working-directory: ${{ github.workspace }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SupersStoryStrings Mod to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # Dynamically set asset_path and asset_name
          asset_path: ./SupersStoryStrings-${{ steps.get_version.outputs.VERSION_NUMBER }}.mod
          asset_name: SupersStoryStrings-${{ steps.get_version.outputs.VERSION_NUMBER }}.mod
          asset_content_type: application/octet-stream

      - name: Upload SupersSpeedStrings Mod to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # Dynamically set asset_path and asset_name
          asset_path: ./SupersSpeedStrings-${{ steps.get_version.outputs.VERSION_NUMBER }}.mod
          asset_name: SupersSpeedStrings-${{ steps.get_version.outputs.VERSION_NUMBER }}.mod
          asset_content_type: application/octet-stream
